[book]
authors = ["kmaitreys"]
language = "en"
src = "src"
title = "citrus: A Primer on Line Modeling"

[build]
build-dir = "../docs/book"

[output.html]
site-url = "/citrus/book"
theme = "theme"
additional-css = ["theme/book.css"]
fold = { enable = true, level = 5 }
git-repository-url = "https://github.com/ProsiaLAB/citrus"
git-repository-icon = "fa-github"
