[package]
name = "citrus"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
blas-src = { version = "0.14.0", features = ["accelerate"] }
codata = "0.2.1"
fitsio = "0.21.10"
ndarray = { version = "0.17.2", features = ["rayon", "serde", "blas"] }
ndarray-linalg = "0.18.1"
planetes-ext = { git = "https://github.com/PlanetesLAB/planetes-ext", tag = "v1.1.0", features = [
    "serde",
] }
qhull = "0.4.0"
rand = "0.10.2"
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
statrs = "0.19.0"
toml = "1.1.3"

[build-dependencies]
autotools = "0.2.7"

[profile.release]
lto = true        # Link-time optimization
codegen-units = 1 # Slower build times, but more optimizationanyhow = "1.0.95"
opt-level = 3     # Highest optimization level
